import express from "express";
import { registerUser } from "../controllers/createUser.js";
import { loginUser } from "../controllers/loginUser.js";
import { forgotPassword } from "../controllers/forgotPassword.js";
import { checkMaintenance } from "../controllers/maintenanceCheck.js";
import { checkActiveUser } from "../middleware/checkActiveUser.js";
import { emailVerify } from "../controllers/emailVerify.js";
import { verifyOtp } from "../controllers/verifyOtp.js";
import { avengersController } from "../controllers/avengersController.js";
import { changePassword, resetPassword } from "../controllers/resetPassword.js";
import { depositConfirmController } from "../controllers/depositConfirmController.js";
import { withdrawController } from "../controllers/withdrawController.js";
import { adminUpdateController } from "../controllers/adminUpdateController.js";
import { adminWithdrawApprovalController } from "../controllers/adminWithdrawApprovalController.js";
import { purchaseNow } from "../controllers/purchaseNow.js";
import { activateGame } from "../controllers/activateGameController.js";
import { adminAveners } from "../controllers/adminAvengers.js";
import { adminTransactionAvengers } from "../controllers/adminTransactionAvengers.js";
import { adminUpdateUserStatus } from "../controllers/adminUserStatusController.js";
import { adminWithdrawFilter } from "../controllers/adminWithdrawFilter.js";
import { sendBulkEmails } from "../controllers/bulkEmailController.js";
import { createPayin,checkPayinStatus } from "../controllers/payment.js";
import { adminUpdatePasscode } from "../controllers/adminUpdatePasscode.js";
import { adminGetDeposits } from "../controllers/adminGetDeposits.js";
const router = express.Router();

router.post("/register", registerUser);
router.post("/login", checkActiveUser ,loginUser);
router.post("/forgot-password", forgotPassword);
router.get("/maintenance-check", checkMaintenance);
router.post("/email-verify", checkActiveUser, emailVerify);
router.post("/verify-otp", checkActiveUser, verifyOtp);
router.post("/reset-password",checkActiveUser, resetPassword);
router.post("/avengers", checkActiveUser , avengersController);
router.post("/confirm", checkActiveUser ,depositConfirmController);
router.post("/withdraw",checkActiveUser, withdrawController);
router.post("/adminUpdate", adminUpdateController);
router.post("/adminUpdatePasscode", adminUpdatePasscode);
router.post("/withdraw-approval", adminWithdrawApprovalController);
router.post("/purchaseNow", checkActiveUser ,purchaseNow);
router.post("/activateGame",checkActiveUser, activateGame);
router.post("/adminAvengers", adminAveners);
router.post("/adminTransactionAvengers", adminTransactionAvengers);
router.post("/adminUpdateUserStatus", adminUpdateUserStatus);
router.post("/adminWithdrawFilter", adminWithdrawFilter);
router.post("/change-password", checkActiveUser ,changePassword);
router.post("/send-bulk-emails", sendBulkEmails);
router.post("/create-payin", createPayin);
router.get("/adminGetDeposits", adminGetDeposits);
// router.post("/webhook", payinWebhook);
router.get("/payin-status/:track_id", checkPayinStatus);

export default router;
