import express from "express";
import { registerUser } from "../controllers/createUser.js";
import { loginUser } from "../controllers/loginUser.js";
import { forgotPassword } from "../controllers/forgotPassword.js";
import { checkMaintenance } from "../controllers/maintenanceCheck.js";
import { checkActiveUser } from "../middleware/checkActiveUser.js";
import { emailVerify } from "../controllers/emailVerify.js";
import { verifyOtp } from "../controllers/verifyOtp.js";
import { avengersController } from "../controllers/avengersController.js";
import { changePassword, resetPassword } from "../controllers/resetPassword.js";
import { depositConfirmController } from "../controllers/depositConfirmController.js";
import { withdrawController } from "../controllers/withdrawController.js";
import { adminUpdateController, getAdminData } from "../controllers/adminUpdateController.js";
import { adminWithdrawApprovalController } from "../controllers/adminWithdrawApprovalController.js";
import { purchaseNow } from "../controllers/purchaseNow.js";
import { activateGame } from "../controllers/activateGameController.js";
import { adminAveners } from "../controllers/adminAvengers.js";
import { adminTransactionAvengers } from "../controllers/adminTransactionAvengers.js";
import { adminUpdateUserStatus } from "../controllers/adminUserStatusController.js";
import { adminWithdrawFilter } from "../controllers/adminWithdrawFilter.js";
import { sendBulkEmails } from "../controllers/bulkEmailController.js";
import { createPayin,checkPayinStatus } from "../controllers/payment.js";
import { adminUpdatePasscode} from "../controllers/adminUpdatePasscode.js";
import { adminGetDeposits } from "../controllers/adminGetDeposits.js";
import { adminDeleteUser } from "../controllers/adminDeletUser.js";
import { convertEarningsToDeposit } from "../controllers/convertEarningsToDeposit.js";
const router = express.Router();

router.post("/register",checkMaintenance, registerUser);
router.post("/login",checkMaintenance, checkActiveUser ,loginUser);
router.post("/forgot-password",checkMaintenance, forgotPassword);
router.get("/maintenance-check",checkMaintenance, checkMaintenance);
router.post("/email-verify",checkMaintenance, checkActiveUser, emailVerify);
router.post("/verify-otp",checkMaintenance, checkActiveUser, verifyOtp);
router.post("/reset-password",checkMaintenance,checkActiveUser, resetPassword);
router.post("/avengers",checkMaintenance, checkActiveUser , avengersController);
router.post("/confirm",checkMaintenance, checkActiveUser ,depositConfirmController);
router.post("/withdraw",checkMaintenance,checkActiveUser, withdrawController);
router.post("/convert-earnings", checkMaintenance, checkActiveUser, convertEarningsToDeposit);
router.post("/adminUpdate", adminUpdateController);
router.get("/getAdminData", getAdminData);
router.post("/adminUpdatePasscode", adminUpdatePasscode);
router.post("/withdraw-approval", adminWithdrawApprovalController);
router.post("/purchaseNow",checkMaintenance, checkActiveUser ,purchaseNow);
router.post("/activateGame",checkMaintenance,checkActiveUser, activateGame);
router.post("/adminAvengers", adminAveners);
router.post("/adminTransactionAvengers", adminTransactionAvengers);
router.post("/adminUpdateUserStatus", adminUpdateUserStatus);
router.post("/adminWithdrawFilter", adminWithdrawFilter);
router.post("/change-password", checkActiveUser ,changePassword);
router.post("/send-bulk-emails", sendBulkEmails);
router.post("/create-payin",checkMaintenance, createPayin);
router.get("/adminGetDeposits", adminGetDeposits);
// router.post("/webhook", payinWebhook);
router.get("/payin-status/:track_id",checkMaintenance, checkPayinStatus);
router.delete("/delete-user",adminDeleteUser)

export default router;
